In [2]:
import numpy as np

In [3]:
np.__version__

'2.2.4'

### Create and Read

In [4]:
### 1d array
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(5,)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.ndim

1

In [9]:
arr1.size

5

#### 2D array   

In [10]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 3)

In [13]:
arr2.dtype

dtype('int64')

##### 3D array

In [14]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [15]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [16]:
arr3.ndim

3

In [17]:
arr3.shape 

(3, 2, 3)

In [18]:
arr3.size

18

### create random array

In [19]:
randomArr = np.random.rand(3,2,3)

In [20]:
randomArr

array([[[0.89149632, 0.19928321, 0.99891582],
        [0.55711024, 0.94362059, 0.93019412]],

       [[0.03465254, 0.4995993 , 0.97097137],
        [0.13655958, 0.37050032, 0.93736809]],

       [[0.19549613, 0.35584784, 0.00622308],
        [0.28463157, 0.96764277, 0.47581795]]])

In [21]:
randomArr.ndim

3

In [22]:
randomArr.size

18

In [23]:
randomArr.shape

(3, 2, 3)

In [24]:
zeroes = np.zeros((3,2,3))

In [25]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
zeroes.ndim

3

In [27]:
full = np.full((3,2,3),8)

In [28]:
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [29]:
ones = np.ones((3,2,3))

In [30]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [31]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [33]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr3[0][0]

array([1, 2, 3])

In [35]:
arr3[0][0][-1]

np.int64(3)

In [37]:
arr3[0:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr3[-1]

array([[13, 14, 15],
       [16, 17, 18]])

In [43]:
a1 = np.random.rand(2,2,3)
a2 = np.random.rand(2,2,3)

In [44]:
a1

array([[[0.88240713, 0.35746648, 0.17917505],
        [0.08407652, 0.64561344, 0.30052106]],

       [[0.3871099 , 0.94681232, 0.00512605],
        [0.6446508 , 0.52787394, 0.9600027 ]]])

In [45]:
a2

array([[[0.2486619 , 0.67248057, 0.88513916],
        [0.1056512 , 0.47832111, 0.36790194]],

       [[0.67941319, 0.6375701 , 0.2791331 ],
        [0.03464523, 0.07747946, 0.89454304]]])

In [48]:
## Basic Math operations
np.add(a1, a2)

array([[[1.13106904, 1.02994705, 1.06431421],
        [0.18972772, 1.12393455, 0.66842301]],

       [[1.06652309, 1.58438242, 0.28425916],
        [0.67929603, 0.6053534 , 1.85454574]]])

In [49]:
np.subtract(a1, a2)

array([[[ 0.63374523, -0.31501409, -0.70596411],
        [-0.02157468,  0.16729232, -0.06738088]],

       [[-0.29230329,  0.30924222, -0.27400705],
        [ 0.61000557,  0.45039448,  0.06545966]]])

In [50]:
np.divide(a1, a2)

array([[[3.54862213e+00, 5.31564025e-01, 2.02425852e-01],
        [7.95793364e-01, 1.34974898e+00, 8.16850985e-01]],

       [[5.69770953e-01, 1.48503250e+00, 1.83641850e-02],
        [1.86072042e+01, 6.81308241e+00, 1.07317665e+00]]])

In [51]:
np.multiply(a1, a2)

array([[[0.21942104, 0.24038926, 0.15859485],
        [0.00888278, 0.30881054, 0.11056228]],

       [[0.26300757, 0.60365923, 0.00143085],
        [0.02233407, 0.04089939, 0.85876373]]])

In [53]:
sqrt = np.sqrt(25)
sqrt

np.float64(5.0)

In [55]:
abs = np.abs(-2)
abs

np.int64(2)

In [56]:
pow = np.power(2,8)
pow

np.int64(256)

In [57]:
log = np.log(25)
log

np.float64(3.2188758248682006)

In [59]:
mins = np.min(a1)
mins

np.float64(0.005126051969970735)

In [61]:
maxs = np.max(a2)
maxs

np.float64(0.8945430388342872)

In [62]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [68]:
arr3[0][0][-1] = 500
arr3

array([[[  1,   2, 500],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]],

       [[ 13,  14,  15],
        [ 16,  17,  18]]])

In [69]:
arr3

array([[[  1,   2, 500],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]],

       [[ 13,  14,  15],
        [ 16,  17,  18]]])

In [70]:
arr3_reshape = arr3.reshape((2,3,3))

In [71]:
arr3_reshape

array([[[  1,   2, 500],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  11,  12],
        [ 13,  14,  15],
        [ 16,  17,  18]]])

##### appending and inserting the array

In [72]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [74]:
new_array = np.ones((3,2,3))

In [75]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [78]:
appnd = np.append(zeroes, ones, axis=0)

In [79]:
appnd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### Inserting into array

In [80]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [82]:
inserted_arr = np.insert(zeroes, 1, new_array, axis=0)# to-array, index, adding-array

In [83]:
inserted_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [87]:
arr4 = np.random.rand(3,2,3)

In [88]:
arr4

array([[[0.46547764, 0.06186779, 0.43558786],
        [0.86252281, 0.73698467, 0.31404087]],

       [[0.108624  , 0.16561653, 0.56861696],
        [0.71597283, 0.49686906, 0.84687219]],

       [[0.52602643, 0.63559182, 0.04956091],
        [0.69134567, 0.27660018, 0.51031494]]])

In [92]:
## delete the array
arr5=np.delete(arr4, 0, axis=1)

In [97]:
np.save("New-arr", arr5)

In [98]:
np.load("New-arr.npy")

array([[[0.86252281, 0.73698467, 0.31404087]],

       [[0.71597283, 0.49686906, 0.84687219]],

       [[0.69134567, 0.27660018, 0.51031494]]])